export const endpoints = {
  REGISTER: '/auth/register',
  REGISTER_LEGAL: '/auth/register-juridical',
  LOGIN: '/auth/login',
  LOGOUT: '/auth/logout',
  ME: '/auth/me',
  CHANGE_PASSWORD: '/auth/change-password',
  UPDATE_USER_DATA: '/api/dealers',
  NOTIFICATION_SETTINGS_DEALERS: '/notifications/dealers',
  ORDERS: '/api/orders',
  RECEIVERS: '/api/receivers',
  RECEIVERS_ADMIN: '/receivers',
  GET_CONTAINERS_BY_ORDER_ID: '/api/containers/by-order',
  HEALTH: '/health',

  ORDERS_ADMIN: '/orders',
  DEALERS_ADMIN: '/dealers',
  CONTAINERS_ADMIN: '/containers',
  GET_CONTAINERS_BY_ORDER_ID_ADMIN: '/containers/by-order',

  ADMINS: '/admins',
  LOGIN_ADMIN: '/admins/login',
  LOGOUT_ADMIN: '/admins/logout',
  CHANGE_PASSWORD_ADMIN: '/admins/change-password',
  STATES: '/api/states',
  STATES_ADMIN: '/states',
  GET_INBOX: '/api/email-api/get-inbox',
  GET_SINGLE_MAIL: '/api/email-api/get-single-mail',

  //Calculator
  UPLOAD_CALCULATOR_DATA: '/calculator/upload',
  AUCTIONS: '/calculator/auctions-list',
  AUCTIONS_AND_LOCATIONS: '/calculator/auction-and-locations',
  LOCATIONS: '/calculator/location-list',
  CARGO_TYPES: '/calculator/cargo-types',
  DESTINATIONS: '/calculator/destination-list',
  CALCULATE_PRICE: '/calculator/calculated-price',
  DOWNLOAD_CALCULATOR_DATA: '/calculator/download',
  DEALER_LEVELS: '/dealer-levels',
  ASSIGN_DEALER_LEVEL: '/dealer-levels/assign-level',
  DOCUMENTS_CHECK: '/documents',
  DOCUMENTS_CHECK_DOWNLOAD: '/documents/download',
  RESET_PASS_INIT: '/auth/password-reset/initiate',
  RESET_PASS_VALIDATE: '/auth/password-reset/validate',
  RESET_PASS_FINALIZE: '/auth/password-reset/finalize',
  MAILINATOR_INBOX: '/mailinator/inbox',
  MAILINATOR_MESSAGE: '/mailinator/message',
}
